create sequence hibernate_sequence start 1 increment 1

create table boarding_adquirencia (id int8 not null, body_json varchar(255), cod_cliente varchar(255),
dt_abrangencia date, id_rede int4, usuario_id varchar(255), primary key (id))


        13jqCe2w

create table cargos (id int4 generated by default as identity, descricao varchar(255), primary key (id))
create table funcionarios (id int4 generated by default as identity, cpf varchar(255), data_contratacao date, nome varchar(255), salario float8, cargo_id int4 not null, primary key (id))
create table funcionarios_unidades (fk_funcionario int4 not null, fk_unidade int4 not null)
create table tb_curso (id int8 not null, cod varchar(255), nome varchar(255), primary key (id))
create table tb_curso_materias (curso_entity_id int8 not null, materias_id int8 not null)
create table tb_materia (id int8 not null, cod varchar(255), freq int4, hrs int4, nome varchar(255), primary key (id))
create table unidade_trabalho (id int4 generated by default as identity, descricao varchar(255), endereco varchar(255), primary key (id))
create table usuario (id varchar(255) not null, primary key (id))
alter table if exists boarding_adquirencia add constraint FK9wxorchl5c3b6j24b9sfhrlur foreign key (usuario_id) references usuario
create sequence hibernate_sequence start 1 increment 1
create table boarding_adquirencia (id int8 not null, body_json varchar(255), cod_cliente varchar(255), dt_abrangencia date, id_rede int4, usuario_id varchar(255), primary key (id))
create table cargos (id int4 generated by default as identity, descricao varchar(255), primary key (id))
create table funcionarios (id int4 generated by default as identity, cpf varchar(255), data_contratacao date, nome varchar(255), salario float8, cargo_id int4 not null, primary key (id))
create table funcionarios_unidades (fk_funcionario int4 not null, fk_unidade int4 not null)
create table tb_curso (id int8 not null, cod varchar(255), nome varchar(255), primary key (id))
create table tb_curso_materias (curso_entity_id int8 not null, materias_id int8 not null)
create table tb_materia (id int8 not null, cod varchar(255), freq int4, hrs int4, nome varchar(255), primary key (id))
create table unidade_trabalho (id int4 generated by default as identity, descricao varchar(255), endereco varchar(255), primary key (id))
create table usuario (id varchar(255) not null, primary key (id))
alter table if exists boarding_adquirencia add constraint FK9wxorchl5c3b6j24b9sfhrlur foreign key (usuario_id) references usuario
alter table if exists funcionarios add constraint FK94l75p7ixitcgh6l240unj9bm foreign key (cargo_id) references cargos
alter table if exists funcionarios_unidades add constraint FKgn3jpmj1h0hdy8io3beyrc13i foreign key (fk_unidade) references unidade_trabalho
alter table if exists funcionarios_unidades add constraint FKg6nq7h4hjl3njvdd4304jp2m0 foreign key (fk_funcionario) references funcionarios
alter table if exists tb_curso_materias add constraint FKil14mxalcsbfq9pu09uta10xa foreign key (materias_id) references tb_materia
alter table if exists tb_curso_materias add constraint FKme6sarj2qmwjdsfvy900fyur9 foreign key (curso_entity_id) references tb_curso
create sequence hibernate_sequence start 1 increment 1
create table boarding_adquirencia (id int8 not null, body_json varchar(255), cod_cliente varchar(255), dt_abrangencia date, id_rede int4, usuario_id varchar(255), primary key (id))
create table cargos (id int4 generated by default as identity, descricao varchar(255), primary key (id))
create table funcionarios (id int4 generated by default as identity, cpf varchar(255), data_contratacao date, nome varchar(255), salario float8, cargo_id int4 not null, primary key (id))
create table funcionarios_unidades (fk_funcionario int4 not null, fk_unidade int4 not null)
create table tb_curso (id int8 not null, cod varchar(255), nome varchar(255), primary key (id))
create table tb_curso_materias (curso_entity_id int8 not null, materias_id int8 not null)
create table tb_materia (id int8 not null, cod varchar(255), freq int4, hrs int4, nome varchar(255), primary key (id))
create table unidade_trabalho (id int4 generated by default as identity, descricao varchar(255), endereco varchar(255), primary key (id))
create table usuario (id varchar(255) not null, primary key (id))
alter table if exists boarding_adquirencia add constraint FK9wxorchl5c3b6j24b9sfhrlur foreign key (usuario_id) references usuario
alter table if exists funcionarios add constraint FK94l75p7ixitcgh6l240unj9bm foreign key (cargo_id) references cargos
alter table if exists funcionarios_unidades add constraint FKgn3jpmj1h0hdy8io3beyrc13i foreign key (fk_unidade) references unidade_trabalho
alter table if exists funcionarios_unidades add constraint FKg6nq7h4hjl3njvdd4304jp2m0 foreign key (fk_funcionario) references funcionarios
alter table if exists tb_curso_materias add constraint FKil14mxalcsbfq9pu09uta10xa foreign key (materias_id) references tb_materia
alter table if exists tb_curso_materias add constraint FKme6sarj2qmwjdsfvy900fyur9 foreign key (curso_entity_id) references tb_curso
create sequence hibernate_sequence start 1 increment 1
create table boarding_adquirencia (id int8 not null, body_json varchar(255), cod_cliente varchar(255), dt_abrangencia date, id_rede int4, usuario_id varchar(255), primary key (id))
create table cargos (id int4 generated by default as identity, descricao varchar(255), primary key (id))
create table funcionarios (id int4 generated by default as identity, cpf varchar(255), data_contratacao date, nome varchar(255), salario float8, cargo_id int4 not null, primary key (id))
create table funcionarios_unidades (fk_funcionario int4 not null, fk_unidade int4 not null)
create table tb_curso (id int8 not null, cod varchar(255), nome varchar(255), primary key (id))
create table tb_curso_materias (curso_entity_id int8 not null, materias_id int8 not null)
create table tb_materia (id int8 not null, cod varchar(255), freq int4, hrs int4, nome varchar(255), primary key (id))
create table unidade_trabalho (id int4 generated by default as identity, descricao varchar(255), endereco varchar(255), primary key (id))
create table usuario (id varchar(255) not null, primary key (id))
alter table if exists boarding_adquirencia add constraint FK9wxorchl5c3b6j24b9sfhrlur foreign key (usuario_id) references usuario
alter table if exists funcionarios add constraint FK94l75p7ixitcgh6l240unj9bm foreign key (cargo_id) references cargos
alter table if exists funcionarios_unidades add constraint FKgn3jpmj1h0hdy8io3beyrc13i foreign key (fk_unidade) references unidade_trabalho
alter table if exists funcionarios_unidades add constraint FKg6nq7h4hjl3njvdd4304jp2m0 foreign key (fk_funcionario) references funcionarios
alter table if exists tb_curso_materias add constraint FKil14mxalcsbfq9pu09uta10xa foreign key (materias_id) references tb_materia
alter table if exists tb_curso_materias add constraint FKme6sarj2qmwjdsfvy900fyur9 foreign key (curso_entity_id) references tb_curso
